### ISSUE TITLE
CSS Tweaks

### ISSUE THREAD

**Issue by Zren** [magne4000/quassel-webserver#3]
Styled  Scrollbars (Webkit only)

``` css
::-webkit-scrollbar {
    width: 8px;
}

::-webkit-scrollbar-track {
    background: transparent;
    border-radius: 4px;
    transition: box-shadow 400ms;
}

::-webkit-scrollbar-track:hover {
    box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
}

::-webkit-scrollbar-thumb {
    border-radius: 4px;
    box-shadow: inset 0 0 6px rgba(0,0,0,1);
}
```

Fix backlog wrapping

``` css
.irc-message { display: table; }
.irc-message > * { display: table-cell; }
/* .message { width: 100%; } // <-- Remove this */
```

Handle topic overflow similar to the client.

``` css
.topic {
min-height: 32px;
}
.topic:hover {
height: initial;
position: relative;
z-index: 1;
}
```
